export const ENGINE_CONFIG = {
  DEFAULT_TICKS_PER_SEC: 64,
  TELEPORT_THRESHOLD_SQ: 6000,
  TRACER: {
    LIFETIME_SEC: 0.15,
    MUZZLE_OFFSET: 24,
  },
  EFFECTS: {
    HE_DURATION_SEC: 0.16,
    SMOKE_DURATION_SEC: 21,
    INFERNO_FALLBACK_SEC: 7,
  }
} as const;